trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.x'
  containerRegistry: 'shongo.azurecr.io'
  imageName: 'fransync-bridging'

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build .NET Projects and Docker Image'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: UseDotNet@2
      displayName: 'Use .NET 9'
      inputs:
        packageType: 'sdk'
        version: $(dotnetVersion)

    - script: |
        dotnet tool install --global GitVersion.Tool --version 5.12.0
        
        # Run GitVersion and capture output as JSON
        GITVERSION_OUTPUT=$(dotnet-gitversion /output json)
        echo "GitVersion JSON Output:"
        echo "$GITVERSION_OUTPUT"
        
        # Parse JSON and extract version values
        SEMVER=$(echo "$GITVERSION_OUTPUT" | jq -r '.SemVer')
        ASSEMBLY_VER=$(echo "$GITVERSION_OUTPUT" | jq -r '.AssemblySemVer')
        FILE_VER=$(echo "$GITVERSION_OUTPUT" | jq -r '.AssemblySemFileVer')
        INFO_VER=$(echo "$GITVERSION_OUTPUT" | jq -r '.InformationalVersion')
        MAJOR_MINOR_PATCH=$(echo "$GITVERSION_OUTPUT" | jq -r '.MajorMinorPatch')
        COMMITS_SINCE_VERSION=$(echo "$GITVERSION_OUTPUT" | jq -r '.CommitsSinceVersionSource')
        
        # Create custom version with build number: Major.Minor.Patch.BuildNumber
        CUSTOM_VERSION="$MAJOR_MINOR_PATCH.$COMMITS_SINCE_VERSION"
        
        # Set pipeline variables for immediate use
        echo "##vso[task.setvariable variable=GitVersionSemVer]$SEMVER"
        echo "##vso[task.setvariable variable=GitVersionAssemblySemVer]$ASSEMBLY_VER"
        echo "##vso[task.setvariable variable=GitVersionAssemblySemFileVer]$FILE_VER"
        echo "##vso[task.setvariable variable=GitVersionInformationalVersion]$INFO_VER"
        echo "##vso[task.setvariable variable=GitVersionMajorMinorPatch]$MAJOR_MINOR_PATCH"
        echo "##vso[task.setvariable variable=GitVersionCustomVersion]$CUSTOM_VERSION"
        
        # Set output variables for later stages
        echo "##vso[task.setvariable variable=Version;isOutput=true]$SEMVER"
        echo "##vso[task.setvariable variable=AssemblyVersion;isOutput=true]$ASSEMBLY_VER"
        echo "##vso[task.setvariable variable=FileVersion;isOutput=true]$FILE_VER"
        echo "##vso[task.setvariable variable=InformationalVersion;isOutput=true]$INFO_VER"
        echo "##vso[task.setvariable variable=CustomVersion;isOutput=true]$CUSTOM_VERSION"
        
        # Display the versions for debugging
        echo "Version: $SEMVER"
        echo "Assembly Version: $ASSEMBLY_VER"
        echo "File Version: $FILE_VER"
        echo "Informational Version: $INFO_VER"
        echo "Major.Minor.Patch: $MAJOR_MINOR_PATCH"
        echo "Custom Version (with build number): $CUSTOM_VERSION"
        echo "Commits Since Version Source: $COMMITS_SINCE_VERSION"
      displayName: 'Install and Run GitVersion'
      name: setVersionVars

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        workingDirectory: 'src/Fransync.Bridging.WebService'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        workingDirectory: 'src/Fransync.Bridging.WebService'
        arguments: '--configuration $(buildConfiguration) --no-restore /p:Version=$(GitVersionSemVer) /p:AssemblyVersion=$(GitVersionAssemblySemVer) /p:FileVersion=$(GitVersionAssemblySemFileVer) /p:InformationalVersion=$(GitVersionInformationalVersion)'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Run tests'
    #   inputs:
    #     command: 'test'
    #     projects: '**/*Tests.csproj'
    #     arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'
    #   continueOnError: true

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'shongo-azure-registry'
        buildContext: '.'
        tags: |
          $(GitVersionCustomVersion)
          latest

- stage: Production
  displayName: 'Deploy to Production'
  dependsOn: BuildAndTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    containerAppName: 'fransync-bridging'
    resourceGroupName: 'prod-fransync-rg'
    version: $[ stageDependencies.BuildAndTest.Build.outputs['setVersionVars.CustomVersion'] ]
    containerImage: '$(containerRegistry)/$(imageName):$(version)'
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy Container to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Configure App Service Port'
            inputs:
              azureSubscription: 'prod-fransync-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Set the correct port for App Service to route to
                az webapp config appsettings set \
                  --name $(containerAppName) \
                  --resource-group $(resourceGroupName) \
                  --settings WEBSITES_PORT=8081

          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: 'prod-fransync-subscription'
              appName: $(containerAppName)
              resourceGroupName: $(resourceGroupName)
              imageName: $(containerImage)
              appSettings: '-ASPNETCORE_ENVIRONMENT Production -ASPNETCORE_URLS http://+:8081 -VERSION $(version)'