trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.x'
  containerRegistry: 'shongo.azurecr.io'
  imageName: 'fransync-bridging'

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build .NET Projects and Docker Image'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 9'
      inputs:
        packageType: 'sdk'
        version: $(dotnetVersion)

    - script: |
        dotnet tool install --global GitVersion.Tool --version 5.12.0
        gitversion /output buildserver
      displayName: 'Install and Run GitVersion'

    - script: |
        echo "##vso[task.setvariable variable=Version;isOutput=true]$GITVERSION_SEMVER"
        echo "##vso[task.setvariable variable=AssemblyVersion;isOutput=true]$GITVERSION_ASSEMBLYSEMVER"
        echo "##vso[task.setvariable variable=FileVersion;isOutput=true]$GITVERSION_ASSEMBLYSEMFILEVER"
        echo "##vso[task.setvariable variable=InformationalVersion;isOutput=true]$GITVERSION_INFORMATIONALVERSION"
        echo "Version: $GITVERSION_SEMVER"
        echo "Assembly Version: $GITVERSION_ASSEMBLYSEMVER"
        echo "File Version: $GITVERSION_ASSEMBLYSEMFILEVER"
        echo "Informational Version: $GITVERSION_INFORMATIONALVERSION"
        echo "Major.Minor.Patch: $GITVERSION_MAJORMINORPATCH"
      displayName: 'Set Version Variables'
      name: setVersionVars

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore /p:Version=$(GITVERSION_SEMVER) /p:AssemblyVersion=$(GITVERSION_ASSEMBLYSEMVER) /p:FileVersion=$(GITVERSION_ASSEMBLYSEMFILEVER) /p:InformationalVersion=$(GITVERSION_INFORMATIONALVERSION)'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'
      continueOnError: true

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        repository: $(imageName)
        dockerfile: 'src/Fransync.Bridging.WebService/Dockerfile'
        buildContext: '.'
        tags: |
          $(GITVERSION_SEMVER)
          $(GITVERSION_MAJORMINORPATCH)
          latest
        arguments: '--build-arg VERSION=$(GITVERSION_SEMVER)'

    - task: Docker@2
      displayName: 'Push Docker Image to ACR'
      inputs:
        command: 'push'
        repository: $(imageName)
        containerRegistry: 'shongo-azure-registry'
        tags: |
          $(GITVERSION_SEMVER)
          $(GITVERSION_MAJORMINORPATCH)
          latest

- stage: Production
  displayName: 'Deploy to Production'
  dependsOn: BuildAndTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    azureSubscription: 'production'
    containerAppName: 'fransync-bridging'
    resourceGroupName: 'prod-fransync-rg'
    version: $[ stageDependencies.BuildAndTest.Build.outputs['setVersionVars.Version'] ]
    containerImage: '$(containerRegistry)/$(imageName):$(version)'
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy Container to Production'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(containerAppName)
              resourceGroupName: $(resourceGroupName)
              imageName: $(containerImage)
              appSettings: |
                -ASPNETCORE_ENVIRONMENT Production
                -ASPNETCORE_URLS http://+:8080
                -VERSION $(version)